import enum

#Chat Channels
class ChatChannel(enum.Enum):
	CHAT_CHANNEL_GLOBAL = 0
	CHAT_CHANNEL_TRADE = 1
	CHAT_CHANNEL_PARTY = 2
	CHAT_CHANNEL_LOOKING_FOR_GROUP = 3
	CHAT_CHANNEL_RAID = 4
	CHAT_CHANNEL_LOCAL_DEFENSE = 5
	CHAT_CHANNEL_ZONE = 6
	CHAT_CHANNEL_GM = 99
